force-di/main/objects/di_Binding__mdt/di_Binding__mdt.object-meta.xml
<CustomObject>
    <label>Binding</label>
    <pluralLabel>Bindings</pluralLabel>
</CustomObject>

force-di/main/objects/di_Binding__mdt/fields/BindingObject__c.field-meta.xml
<CustomField>
    <fullName>BindingObject__c</fullName>
    <label>Binding Object</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>Bindings</relationshipLabel>
    <relationshipName>Bindings</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-di/main/objects/di_Binding__mdt/fields/BindingSequence__c.field-meta.xml
<CustomField>
    <fullName>BindingSequence__c</fullName>
    <label>Binding Sequence</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-di/main/default/objects/DI_Binding__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apex</fullName>
                <default>true</default>
                <label>Apex</label>
            </value>
            <value>
                <fullName>LightningComponent</fullName>
                <label>Lightning Component</label>
            </value>
            <value>
                <fullName>VisualforceComponent</fullName>
                <label>Visualforce Component</label>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
            <value>
                <fullName>Module</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-di/main/classes/di_BindingConfigWrapper.cls
global with sharing class di_BindingConfigWrapper {
    // Constructor to inject the data through test class.
    global di_BindingConfigWrapper(   String qualifiedAPIName
                                    , String developerName
                                    , String namespacePrefix
                                    , String type
                                    , String to
                                    , String bindingObject
                                    , String bindingObjectQualifiedApiName
                                    , String bindingObjectAlternate
                                    , Decimal bindingSequence){
        this.QualifiedAPIName = qualifiedAPIName;
        this.DeveloperName = developerName;
        this.NamespacePrefix = namespacePrefix;
        this.Type = type;
        this.To = to;
        this.BindingObject = bindingObject;
        this.BindingObjectQualifiedApiName = bindingObjectQualifiedApiName;
        this.BindingObjectAlternate = bindingObjectAlternate;
        this.BindingSequence = bindingSequence;
    }
   //Constructor to inject the data  from a metadata  by giving reference of metadata
    global di_BindingConfigWrapper(di_Binding__mdt bindingConfig){
        this.QualifiedAPIName = bindingConfig.QualifiedApiName;
        this.DeveloperName = bindingConfig.DeveloperName;
        this.NamespacePrefix = bindingConfig.NamespacePrefix;
        this.Type = bindingConfig.Type__c;
        this.To = bindingConfig.To__c;
        this.BindingObject = bindingConfig.BindingObject__c;
        this.BindingObjectQualifiedApiName = bindingConfig.BindingObject__r.QualifiedApiName;
        this.BindingObjectAlternate = bindingConfig.BindingObjectAlternate__c;
        this.BindingSequence = bindingConfig.BindingSequence__c;
    }
    global String QualifiedAPIName{get;set;}
    global String DeveloperName{get;set;}
    global String NamespacePrefix{get;set;}
    global String Type{get;set;}
    global String To{get;set;}
    global String BindingObject{get;set;}
    global String BindingObjectQualifiedApiName{get;set;}
    global String BindingObjectAlternate{get;set;}
    global Decimal BindingSequence{get;set;}
}